### ISSUE TITLE
error on install

### ISSUE THREAD

**Issue by AllyPallies** [pangolp/support#1]
```php
Error Number: 1050

Table 'realms' already exists

CREATE TABLE `realms` ( `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT, `hostname` VARCHAR(100) NOT NULL DEFAULT '127.0.0.1', `username` VARCHAR(255) NOT NULL, `password` VARCHAR(255) NULL, `char_database` VARCHAR(255) NOT NULL, `realmID` INT(10) UNSIGNED NOT NULL, `console_hostname` VARCHAR(100) NOT NULL DEFAULT '127.0.0.1', `console_username` VARCHAR(255) NOT NULL, `console_password` VARCHAR(255) NOT NULL, `console_port` INT(6) UNSIGNED NOT NULL DEFAULT '7878', `emulator` VARCHAR(255) NOT NULL DEFAULT 'TC', CONSTRAINT `pk_realms` PRIMARY KEY(`id`) ) DEFAULT CHARACTER SET = utf8 COLLATE = utf8_general_ci

Filename: C:/xampp/htdocs/system/database/DB_driver.php

Line Number: 691
```

**Comment by pangolp** [comment]
Hi, thanks for the report. To help you, I need you to answer a series of questions to get information about the problem.

1- What operating system are you using?
2- Is it a local server, webhosting, vps?
3- What version of php are you using?
4- Where did you get the code?
That is, from the web, from the repository.
If from the repository, what branch are you using (master / refactor)

**Comment by AllyPallies** [comment]
I would really love to move this over to my VPS but im having a little bit of issues to make that happen.
1) Windows 10
2) local but at some point once i understand it better will be on a VPS thats running Linux
3) PHP 7.4
4) From the main repo on Gitlab
5) Its the master

**Comment by pangolp** [comment]
The tables within the CMS are created through migrations. If you execute `/en/dbmigrate`, it executes them. Basically what the error says, is that you can't create the database `realms`, because it already exists. Until now, I have never had this problem in an installation. Please let me know if running `dbmigrate` solves the problem.

**Comment by pangolp** [comment]
Basically, the error is that you want to generate a table that already exists. In SQL, you can't do a `CREATE`, without a `DROP TABLE`. But the CMS, doesn't use SQL, it used `migrations`. That they are files, that you configure, to take a history of the changes, without having to write SQL. It has 2 main methods, `up()` and `down()`. In `up()` in your case, the table would have to be `created`, and in `down()` usually the opposite is done, in this case removing it.

**Comment by pangolp** [comment]
https://gitlab.com/WoW-CMS/BlizzCMS-Plus/-/blob/master/application/migrations/022_create_realms.php
That is the migration, which takes care of creating the table, as well as eliminating it.
