### ISSUE TITLE
[Soporte en Español] Error al registrar intentar registrar un usuario.

### ISSUE THREAD

**Issue by jhoancito** [pangolp/support#12]
# Wow-CMS: Soporte en español

##### ¿Qué sistema operativo estás usando?
- [x] Windows

##### ¿Qué versión de PHP utiliza?
- [x] PHP 7.x

##### ¿De dónde conseguiste el código del CMS?
- [x] Github

##### ¿Dónde está tratando de instalar el CMS?
- [x] Servidor local

##### ¿Qué emulador estás usando y qué versión?
- [x] TrinityCore

##### Describa el bug

Al crear nueva cuenta da error 

##### ¿Cómo puedo reproducir el problema?

Al intentar registrar la cuenta me sale el siguiente error.

##### Capturas de pantalla

![register](https://user-images.githubusercontent.com/2810187/121828150-205b9b80-cc95-11eb-8471-f7b8f8edf020.png)

**Comment by pangolp** [comment]
Ese error se produce, porque elegiste una opción incorrecta a la hora de instalar el `CMS`. Actualmente el `CMS` le da soporte a muchos tipos de servidores, versiones nuevas y antiguas de `TrinityCore`, `AzerothCore`, `SkyFire`, `CMaNGOS` entre otros. Es por eso, que al momento de realizar la instalación, le pregunta sobre el uso de `SRP6`, `bnet` y varias opciones más. Si elegís la opción incorrecta, tendrás que realizar la estructura de tu base de datos, y realizar los cambios correspondientes, para que el `CMS` funcione de manera correcta.

**Comment by jhoancito** [comment]
si ya lo solucione tenias razon era en el emulador el error
