### ISSUE TITLE
[Soporte en Español] Error al configurar el realm

### ISSUE THREAD

**Issue by jhoancito** [pangolp/support#13]
# Wow-CMS: Soporte en español

##### ¿Qué sistema operativo estás usando?
- [x] Windows

##### ¿Qué versión de PHP utiliza?
- [x] PHP 7.x

##### ¿De dónde conseguiste el código del CMS?
- [x] Github

##### ¿Dónde está tratando de instalar el CMS?
- [x] Servidor local

##### ¿Qué emulador estás usando y qué versión?
- [x] TrinityCore

##### Describa el bug
- El error es al agregar reino ala web 

##### Capturas de pantalla

![realms_1](https://user-images.githubusercontent.com/2810187/122132893-0d220a80-ce12-11eb-8939-dcf03598910d.png)

![realms_2](https://user-images.githubusercontent.com/2810187/122132896-101cfb00-ce12-11eb-98dc-a0708804df9a.png)

**Comment by pangolp** [comment]
Este error, normalmente ocurre, cuando tenes problemas en la conexión a la base de datos, posiblemente porque la contraseña tiene algún caracteres especial, o quizás tiene una longitud un poco extensa, en fin, pueden ser muchos los factores, te recomiendo que pruebes la conexión primero y luego cuando sepas que funciona correctamente, realices la conexión.
