### ISSUE TITLE
[Soporte en Español] Problemas con el carrito de compras

### ISSUE THREAD

**Issue by jhoancito** [pangolp/support#14]
# Wow-CMS: Soporte en español

##### ¿Qué sistema operativo estás usando?
- [x] Windows

##### ¿Qué versión de PHP utiliza?
- [x] PHP 7.x

##### ¿De dónde conseguiste el código del CMS?
- [x] Github

##### ¿Dónde está tratando de instalar el CMS?
- [x] Servidor local

##### ¿Qué emulador estás usando y qué versión?
- [x] TrinityCore

##### Describa el bug
- el visualización del carrito de store ya verifique soap todo bien igual sale lo mismo compre no se compra para nada no me entrega ni al dentro del juego 

##### Capturas de pantalla
![cart](https://user-images.githubusercontent.com/2810187/122132398-2a0a0e00-ce11-11eb-9bee-d35ff48274b6.png)

**Comment by pangolp** [comment]
Revisa, en la base de datos de la web, si el ID del `realmlist` del juego, coincide con el id del store. Es un tema complicado de explicar, pero ambos números deben coincidir. Si no es ese el problema, entonces quizás sea algo relacionado a la contraseña de la base de datos.
```sql
SELECT `id`, `realmID` FROM `realms`;
```
![realms](https://user-images.githubusercontent.com/2810187/122132050-86b8f900-ce10-11eb-8028-da1e3cba691f.png)
