### ISSUE TITLE
[Soporte en Español] error poner item en top en store

### ISSUE THREAD

**Issue by jhoancito** [pangolp/support#15]
# Wow-CMS: Soporte en español

##### ¿Qué sistema operativo estás usando?
- [x] Windows

##### ¿Qué versión de PHP utiliza?
- [x] PHP 7.x

##### ¿De dónde conseguiste el código del CMS?
- [x] Github

##### ¿Dónde está tratando de instalar el CMS?
- [x] Servidor local

##### ¿Qué emulador estás usando y qué versión?
- [x] TrinityCore

##### Describa el bug
- Agrego ítem en top sale error 

##### Capturas de pantalla
![topstore](https://user-images.githubusercontent.com/2810187/122132520-63427e00-ce11-11eb-844b-32e213065a63.png)

**Comment by pangolp** [comment]
Ese error, ya fue fixeado, todavía falta que se agregue al código del CMS.
Te dejo un enlace para que veas cuando el mismo sea aprobado.

**Comment by pangolp** [comment]
https://github.com/WoW-CMS/BlizzCMS/pull/14

**Comment by pangolp** [comment]
Se acaba de incorporar el código que corrige ese error. Así que si actualizas el mismo, debería de desaparecer.
