### ISSUE TITLE
[Soporte en Español] Problemas con el modulo de donación.

### ISSUE THREAD

**Issue by SanemiWOW** [pangolp/support#16]
# Wow-CMS: Soporte en español

##### ¿Qué sistema operativo estás usando?
- [x] Windows

##### ¿Qué versión de PHP utiliza?
- [x] PHP 7.x

##### ¿De dónde conseguiste el código del CMS?
- [x] Github

##### ¿Dónde está tratando de instalar el CMS?
- [x] VPS

##### ¿Qué emulador estás usando y qué versión?
- [x] TrinityCore

##### Describa el bug
- Problema con el modulo de Donación, cuando intento generar una donación y que debería de cargar la API para poder hacer el pago la web queda en Blanco y no sale ningún error. Intente borrar la API hacerla de nuevo esperar unas horas para intentar nuevamente pero nada siempre termino en el mismo lugar.

##### Capturas de pantalla
![unknown2](https://user-images.githubusercontent.com/86812776/124210085-3785f000-dac1-11eb-9a0b-bd7b48e9b0b7.jpg)

**Comment by pangolp** [comment]
Lo primero que tenemos que probar, en este caso, es si necesitamos tener si o si, un certificado SSL, es decir, un dominio HTTPS, porque quizás como PayPal se encarga de hacer transacciones, es probable que necesite que el sitio del que se esta intentando hacer la misma, disponga de este certificado. Si no llega a ser eso, entonces seguiremos investigando.

**Comment by pangolp** [comment]
Problema resuelto. Seguramente era alguna configuración del WAMP server. Se probo de cambiar a XAMPP y funciono sin problemas. Así que doy por cerrado el tema.
