### ISSUE TITLE
[Soporte en Español] Tienda

### ISSUE THREAD

**Issue by Rosencrant** [pangolp/support#17]
# Wow-CMS: Soporte en español

##### ¿Qué sistema operativo estás usando?
- [x] Windows

##### ¿Qué versión de PHP utiliza?
- [x] PHP 8.x

##### ¿De dónde conseguiste el código del CMS?
- [x] Github

##### ¿Dónde está tratando de instalar el CMS?
- [x] Servidor local

##### ¿Qué emulador estás usando y qué versión?
- [x] TrinityCore

##### Describa el bug
- En realidad no es un buen, intento poner en la tienda por ejemplo una subida a nivel 80 o subida de profesiones y no estaría funcionando en absoluto. Los ítems si llegan al comprarse y no estaría logrando solucionarlo.

##### ¿Cómo puedo reproducir el problema?

1. Crear en la tienda una venta de subida de nivel.

**Comment by pangolp** [comment]
Viendo y considerando que estas usando PHP 8, cuando el CMS por temas de compatibilidad no debería de funcionar con el, no me sorprende que la tienda no funcione. Luego de eso, la tienda funciona mediante comandos, pero no requiere que lo pongas, simplemente que selecciones la opción que queres (por ejemplo: la subida al personaje a un cierto nivel) y que donde dice comando, pongas el nivel, no el comando. Puede que suene medio extraño, pero la idea, no es que tengan que usar los comandos justamente, si no, tratar de facilitar un poco ese tema. Aguardo tu respuesta.

**Comment by Rosencrant** [comment]
Perdon la demora, la web esta en PHP 7.2.4 o algo era. quedo solucionado eso que consulte. mi pregunta es ahora. el sistema de Logs de donaciones esta mal o hay que habilitarlo de alguna manera? y los items cuando se agregan algunos fallan en lo que dice. y otra duda que tengo por ejemplo es que si quisiera poner venta de Profesiones es posible?

**Comment by pangolp** [comment]
Vamos por partes.

- Los logs de las donaciones, actualmente la única forma de verlos, es a través de la base de datos.
(No es posible verlo desde el administrador de momento, es algo pendiente que se iba a agregar)

- Si los items no llegan, debería de comprobar bien la conexión soap, permisos, puertos, usuarios.
(De momento, si esta todo bien configurado de no debería de haber problema)

- Actualmente el modulo de tienda, esta diseñado, para que no se puedan agregar comandos custom, solamente los que se mencionan en el select, cuando estas creando el ítem de la tienda. En un principio, la idea fue facilitar la tarea, así que creo que de momento, no se podrían agregar profesiones. Habría que editar el modulo, y agregarlas como una opción mas.

**Comment by pangolp** [comment]
Cierro el tema, cualquier cosa, si tiene mas problemas, abriremos un nuevo tema. De todos modos, no lo haga aquí. Hágalo en: https://www.github.com/wow-cms/support
