### ISSUE TITLE
[English]: module "donate", support for other payment systems

### ISSUE THREAD

**Issue by Tomix1** [pangolp/support#18]
### What operating system are you using?

Linux

### What version of PHP do you use?

PHP 7.x

### Where did you get the CMS code?

Github

### Where are you trying to install the CMS?

VPS

### Which emulator are you using and which version?

Other

### How can I reproduce the problem?

Hello!
Did I understand correctly that the "donate" module now only supports payment via PayPal. And there is no easy way to add another payment system now? That is, to add another payment system, do I need to rewrite the PayPal code in the "donate" module, or implement the functionality of adding new payment systems using modules?

**Comment by pangolp** [comment]
For the moment, yes. This is the only payment method that has been developed. Later on, we will try to add more, but for the moment it is the only one. If you want to collaborate, adding new payment systems, we will be happy to receive the code to be able to add it to the CMS.
