### ISSUE TITLE
[Soporte en Español] Puerto de MySQL diferente del 3306.

### ISSUE THREAD

**Issue by jhoancito** [pangolp/support#19]
# Wow-CMS: Soporte en español

##### ¿Qué sistema operativo estás usando?
 Windows 7 ultimate

##### ¿Qué versión de PHP utiliza?
 PHP 7.x

##### ¿De dónde conseguiste el código del CMS?

 Github

##### ¿Dónde está tratando de instalar el CMS?
Servidor local

##### ¿Qué emulador estás usando y qué versión?

TrinityCore

##### Describa el bug
- mi Mysql esta puerto 3307 y mi xampp puerto 3306 me da error al instalar blizzcms

##### ¿Cómo puedo reproducir el problema?

1.
2.
3.
4.

##### Capturas de pantalla

```
A PHP Error was encountered
Severity: Warning

Message: mysqli::real_connect(): (HY000/1045): Access denied for user 'root'@'localhost' (using password: YES)

Filename: mysqli/mysqli_driver.php

Line Number: 203

Backtrace:

File: C:\xampp\htdocs\application\third_party\MX\Loader.php
Line: 139
Function: DB

File: C:\xampp\htdocs\application\third_party\MX\Loader.php
Line: 68
Function: initialize

File: C:\xampp\htdocs\application\controllers\General.php
Line: 43
Function: __construct

File: C:\xampp\htdocs\index.php
Line: 320
Function: require_once

A Database Error Occurred
Unable to connect to your database server using the provided settings.

Filename: C:/xampp/htdocs/system/database/DB_driver.php

Line Number: 436
```

**Comment by pangolp** [comment]
Si lo que necesitas es usar un puerto diferente del 3306, que es el que usa por defecto la conexión de MySQL. Tenes que ir al archivo de configuración de base de datos, y especificarle el puerto, donde dice `hostname`. De la siguiente forma:

![puerto](https://user-images.githubusercontent.com/2810187/158899173-a2746bff-1039-43b3-a5c4-7d91e3c149d3.png)
