### ISSUE TITLE
Problema con el widget de discord.

### ISSUE THREAD

**Issue by carlitos022** [pangolp/support#2]
# Wow-CMS: Soporte en español

Hola y bienvenido. Antes de empezar tenemos que hacerte un par de preguntas. Eso nos ayudará a tener la información necesaria, y luego, tratar de darle el mejor apoyo posible.

### Wow-CMS: Soporte en español

Hola y bienvenidos. Antes de empezar necesitamos hacerte un par de preguntas. Eso nos ayudará a tener la información necesaria, y luego, intentar darte el mejor soporte posible. **¿Por qué usamos este medio y no contestamos directamente en discord?** *Simplemente, porque a través de tema, primero, se encierra todo el tema en una sola conversación y por otro lado, una vez resuelto el tema, puede ser útil para otras personas, ya que aunque el tema esté cerrado, sigue siendo visible y podemos facilitar el enlace a otra persona en el futuro que tenga el mismo problema.*

##### ¿Qué sistema operativo estás usando?

Hostinger hosting web el servidor en un linux debian 10
##### ¿Qué versión de PHP utiliza?
en el vps del servidor ni uno tengo hosting para la web
##### ¿De dónde sacaste el código del CMS?
https://gitlab.com/WoW-CMS/BlizzCMS-Plus

##### ¿Dónde está tratando de instalar el CMS?

En un hosting web hostinger
##### ¿Qué emulador estás usando y qué versión?
azerothcore la ultima versión en un vps con debian 10

##### Describa el bug
Ya instale el ultimo repositorio master de blizzcms y tengo problemas con el banner del discord ya intente de varias formas y sigue ese logo como dañado.

##### ¿Cómo puedo reproducir el problema?

1.No se observa el banner
2. Si abre el discord al abrir esa imagen como dañada
3.Link de la invitacion del dc de 10 digitos
4.Intentos de Varias formas

##### Capturas de pantalla

![foto](https://user-images.githubusercontent.com/57599543/106401777-31aeb480-6426-11eb-8b1d-966f45a14dee.jpg)

**Comment by pangolp** [comment]
Hola, ¿tenes habilitado el widget dentro del servidor de discord?

![widget](https://user-images.githubusercontent.com/2810187/106401853-4d559300-6405-11eb-81d8-254a33da6993.png)

Si el widget esta habilitado, lo que tenes que hacer, es revisar que donde pide el discord, no tenes que poner la URL entera, si no, las solo el contenido de la invitación. Por ejemplo, si la invitación es esta: https://discord.com/invite/fXkHj6GcZm lo que tenes que agregar, ya sea durante la instalación o en el formulario dentro del admin, es lo siguiente: **fXkHj6GcZm**.

**Comment by carlitos022** [comment]
ya probé bro nada ya intente

**Comment by pangolp** [comment]
Ok, lo que tendrías que fijarte entonces, es que dentro del archivo de configuración del modulo home, existe un fichero, que te permite editar la cantidad de caracteres que tiene la invitación. Las invitaciones anteriormente, tenían 7 caracteres, pero las nuevas, tienen 10. Revisa que valor tiene, y en base a tu invitación, ponele el valor que le corresponda.
https://gitlab.com/WoW-CMS/BlizzCMS-Plus/-/blob/master/application/modules/home/config/home.php#L20

**Comment by carlitos022** [comment]
Listo muchas gracias esa fue la solución perfecto muchas gracias
![discord](https://user-images.githubusercontent.com/57599543/106402700-02e70d00-642b-11eb-800e-84edbad92a6b.jpg)

**Comment by pangolp** [comment]
De nada.
