### ISSUE TITLE
[English support] Installation error

### ISSUE THREAD

**Issue by cutdachez** [pangolp/support#3]
### Wow-CMS English support

Hello and welcome. Before we start we need to ask you a couple of questions. That will help us to have the necessary information, and then, try to give you the best possible support. **Why do we use this medium and not answer directly on discord?** *Simple, because through issue, first, the whole issue is enclosed in a single conversation and on the other hand, once the issue is solved, it can be useful for other people, because even though the issue is closed, it is still visible and we can provide the link to another person in the future who has the same problem.*

##### What operating system are you using?
win server 2016

##### What version of PHP do you use?
latest xampp

##### Where did you get the CMS code?
wow-cms.com

##### Where are you trying to install the CMS?
VPS

##### Which emulator are you using and which version?

latest BFA

##### Describe the bug
issue creating new site. When i go to. http://yourip.com/ It does not load. Because it shows adds/en/migrate / If I remove the "en" it goes to migration page. however migration ends up failing. "more to follow"(edited)
[12:46 PM]
Using new download of cms. setting it to bfa core. hosting on a vps using xampp. After i do the migration I get the following  The migration class "Migration_Create_ci_sessions" is missing an "up" method

##### How can I reproduce the problem?

1.
2.
3.
4.

##### Screenshots
![unknown23452342453234525](https://user-images.githubusercontent.com/43968878/106959190-f818ca80-66ff-11eb-9d3c-a4ceb0dc23b6.png)

**Comment by pangolp** [comment]
Hello, Good afternoon. The problem is probably due to the PHP version. If you are using the latest version of XAMPP, surely you downloaded the 8.x version of php, you have to download and install a previous one, one that brings php 7.x. I leave you the link, and let me know if it works with that. https://www.apachefriends.org/download.html

![xampp](https://user-images.githubusercontent.com/2810187/106960777-57380880-671b-11eb-92ff-6c03b9d786e2.png)

**Comment by pangolp** [comment]
On the other hand, I recommend you to use the code from the repository. It is a bit more up to date than the one on the web. Since in the web, you work by versions, and in the repository, some changes have been made that are not yet uploaded.
https://gitlab.com/WoW-CMS/BlizzCMS-Plus/

**Comment by pangolp** [comment]
Anyway, BFA I believe is supported in the `refactor` branch of the repository. In master, there is no such enhancement yet. If you see that for some reason, it doesn't work, I recommend you to try with the following code: https://gitlab.com/WoW-CMS/BlizzCMS-Plus/-/tree/refactor

**Comment by cutdachez** [comment]
correcting it now

**Comment by cutdachez** [comment]
Solved thanks
