### ISSUE TITLE
[Soporte en Español]

### ISSUE THREAD

**Issue by victhorinox** [pangolp/support#4]
# Wow-CMS: Soporte en español

Hola y bienvenido. Antes de empezar tenemos que hacerte un par de preguntas. Eso nos ayudará a tener la información necesaria, y luego, tratar de darle el mejor apoyo posible.

### Wow-CMS: Soporte en español

Hola y bienvenidos. Antes de empezar necesitamos hacerte un par de preguntas. Eso nos ayudará a tener la información necesaria, y luego, intentar darte el mejor soporte posible. **¿Por qué usamos este medio y no contestamos directamente en discord?** *Simplemente, porque a través de tema, primero, se encierra todo el tema en una sola conversación y por otro lado, una vez resuelto el tema, puede ser útil para otras personas, ya que aunque el tema esté cerrado, sigue siendo visible y podemos facilitar el enlace a otra persona en el futuro que tenga el mismo problema.*

##### ¿Qué sistema operativo estás usando?
Linux - Web Hosting cPanel

##### ¿Qué versión de PHP utiliza?
Version PHP 7.1.33

##### ¿De dónde sacaste el código del CMS?
Se descargo desde la pagina oficial del CMS.

##### ¿Dónde está tratando de instalar el CMS?
Esta instalado correctamente en un Web Hosting cPanel

##### ¿Qué emulador estás usando y qué versión?
Se esta usando AzerothCore 3.3.5a

##### Describa el bug
Instale BlizzCMS en un Web Hosting cPanel. En general todo funciona bien: registrar, iniciar sesion, etc.
Pero hay un detalle en la tienda de item:

Los datos del reino están configurados correctamente en la web: Se creo un usuario con todos los privilegios con acceso remoto para instalar la Web.

Al entrar a la tienda desde el panel de usuario y comprar un artículo. En la web indica que la compra se completó pero al ingresar al juego no aparece el artículo comprado.

##### Capturas de pantalla

http://imgfz.com/i/qsa02lZ.jpeg

En Worldserver.conf tengo la IP Publica del VPS en el soap.ip
http://imgfz.com/i/rq3phNu.jpeg

**Comment by pangolp** [comment]
Hola buenas noches. Para poder utilizar la tienda, necesitas primero hacer una configuraciones respeto a SOAP. Tanto en el emulador, como en la web. El problema de la versión que estas usando (que es la de la web), es que por ejemplo, cuando creas el reino, dentro del admin, no te aparece el emulador, y por defecto utiliza TrinityCore. Tenes 2 alternativas, o cambias la versión, utilizando la del repositorio, o entras en la base de datos del CMS, buscas la tabla de reinos, y donde dice `emulator` pones AC (que es para emuladores basados en `AzerothCore`.

Para testear la conexión de sopa, podes utilizar una URL, que solo esta disponible para los administradores.
Para acceder a ellas, logueas con una cuenta admin, y en la URL, luego de `/admin`, agregas: `/checksoap`.
Si al entrar en esa URL, te aparece un `server info`, entonces significa que soap esta correctamente configurado.
Si no, hay que configurarlo y eso puede depende de muchos factores.
```sql
UPDATE `realms` SET `emulator`='AC' WHERE `id`=;
```
El id del reino, depende de tu servidor. Luego del = pone el numero correspondiente.
Aunque te recomiendo utiliza la versión del repositorio, que esta un poco mas actualizada que la de la web.
https://gitlab.com/WoW-CMS/BlizzCMS-Plus/

**Comment by victhorinox** [comment]
Muchas gracias mi estimado. Preferi instalar el nuevo repositorio y va excelente. Gracias puedes cerrar el tema.
