### ISSUE TITLE
[English support] Shadowlands

### ISSUE THREAD

**Issue by cutdachez** [pangolp/support#5]
### Wow-CMS English support

Hello and welcome. Before we start we need to ask you a couple of questions. That will help us to have the necessary information, and then, try to give you the best possible support. **Why do we use this medium and not answer directly on discord?** *Simple, because through issue, first, the whole issue is enclosed in a single conversation and on the other hand, once the issue is solved, it can be useful for other people, because even though the issue is closed, it is still visible and we can provide the link to another person in the future who has the same problem.*

##### What operating system are you using?
win 2016 server

##### What version of PHP do you use?

7.4
##### Where did you get the CMS code?

wow-cms
##### Where are you trying to install the CMS?
xampp

##### Which emulator are you using and which version?
Trinity-Shadowlands

##### Describe 
Shop is failing. Go to cart to purchase item all I get if the window that says checking information. But it never makes purchase. 
Soap is enabled in php.ini -enabled in worldserver.conf -soap account created with character created. 
Have checked password and info for soap. Not sure what I am missing. 
I have changed the cms as I have in past for it to work to allow SL. Accounts when created do get SL designation. I checked.
I am at a loss on what it could be.

![fail_shop1](https://user-images.githubusercontent.com/43968878/108782943-238a1a80-7532-11eb-8cbe-8c5487ab4a58.jpg)

##### How can I reproduce the problem?

1.
2.
3.
4.

**Comment by pangolp** [comment]
Hello, good evening. The Shadowlands truth is just a few months old, I don't know if the CMS is really ready to support it. Until BFA, I knew there were no problems, but with this latest expansion, I really don't know, I will try to find out about it, but I really doubt it will work. The expansion came out in November / December last year.

**Comment by pangolp** [comment]
I recommend you not to use the web version, because it is a bit outdated, the ideal is to use what is in the repository, where some changes have been made. https://gitlab.com/WoW-CMS/BlizzCMS-Plus. Master, I don't think it supports the latest versions of TrinityCore yet. You can check, the refactor branch. But it is a branch that is not yet complete.

**Comment by cutdachez** [comment]
It worked for me before. On another SL server. Not sure why it is not working now. Accounts register as SL expansion, Just having issues with shop I did not have last time.

**Comment by cutdachez** [comment]
Using the repo version solved the issue. Shop now works. Thanks

**Comment by pangolp** [comment]
You're welcome.
