### ISSUE TITLE
[English support]: Can't edit Forum Topics

### ISSUE THREAD

**Issue by Lenzork** [pangolp/support#7]
# Wow-CMS English support

### What operating system are you using?
- [X] Linux

### What version of PHP do you use?
- [X] PHP 7.x

### Where did you get the CMS code?
- [X] Github

### Where are you trying to install the CMS?
- [X] Dedicated server

### Which emulator are you using and which version?
- [X] TrinityCore

### Describe the bug
The EDIT TOPIC Button disappears and does simply nothing (?)

### How can I reproduce the problem?

1. Go into the Forum and create a Topic
2. Go into the Topic
3. Click the Button on the Top right that says "EDIT TOPIC"
4. Then (for atleast) it disappears

### Screenshots
https://i.ibb.co/dg0R54G/First.png <- Before the Click
https://i.ibb.co/TbWLV9W/second.png <- After the Click

**Comment by pangolp** [comment]
I close the subject, because it is something related to development. I hope I have answered your question.
